config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, skip: [:destroy]
  devise_for :users, skip: [:registrations]

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/send_payroll', to: 'dashboard#send_payroll'
    put '/update_status', to: 'dashboard#update_status' 
    get '/stores/export-weekly', to: 'stores#export_week'
    resources :users do
      member do
        get :toggle_status
      end
    end
    resources :stores
    resources :services
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :posts, dependent: :destroy
  validates_presence_of :service_name, :pay_time
  belongs_to :store
  
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < ApplicationController
    layout 'admin'
    before_action :authenticate_admin
    before_action :set_service, only: [:show, :edit, :update, :destroy]
    
    def index
      @services = Service.all
      @stores = Store.all
    end

    def new
      @service = Service.new
    end

    def create
      @service = Service.new(service_params)
      if @service.save!
        redirect_to admin_services_path, notice: "Service Created"
      else
        render :new
      end
    end

    def show
      
    end

    def edit
      
    end

    def update
      if @service.update(service_params)
        redirect_to admin_services_path, notice: "#{@service.service_name} has been updated"
      else
        render :edit
      end
    end

    def destroy
      
    end

    private

    def service_params
      params.require(:service).permit(:service_name, :store_id, :description, :pay_time)
    end

    def set_service
      @service = Service.find(params[:id])
      @stores = Store.all
    end
    
    
  end
end

app/views/admin/services/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Services</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add Service</h5>
          <%= form_for :service, :url => admin_service_path(@service), method: :put do |f| %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :service_name %>
                <%= f.text_field :service_name, class: 'form-control form-control-sm' %>
              </div>
            </div>
            <div class="col">
              <%= f.label "Pay Amount" %>
              <%= f.number_field :pay_time, step: 0.5, class: 'form-control form-control-sm' %>
            </div>
            <div class="col">
              <%= f.collection_select(:store_id, @stores, :id, :name) %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control form-control-sm' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.submit "Edit", class: 'btn btn-primary btn-sm' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Services</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add Service</h5>
          <%= form_for :service, :url => admin_services_path do |f| %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :service_name %>
                <%= f.text_field :service_name, class: 'form-control form-control-sm' %>
              </div>
            </div>
            <div class="col">
              <%= f.label "Pay Amount" %>
              <%= f.number_field :pay_time, step: 0.5, class: 'form-control form-control-sm' %>
            </div>
            <div class="col">
              <%= f.collection_select(:store_id, @stores, :id, :name) %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control form-control-sm' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.submit "Add Service", class: 'btn btn-primary btn-sm' %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-tabs" role="tablist">
        <% @stores.each do |store| %>
          <li class="nav-item">
            <a class="nav-link" href="#store<%= store.id %>" role="tab" data-toggle="tab"><%= store.name %></a>
          </li>
        <% end %>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <% @stores.each do |store| %>
          <div role="tabpanel" class="tab-pane fade" id="store<%= store.id %>">
            <table class="table table-striped table-sm">
              <thead>
                <th>Service Name</th>
                <th>Hours/Pay</th>
                <th></th>
              </thead>
              <tbody>
                <% store.services.each do |service| %>
                  <tr>
                    <td><%= service.service_name %></td>
                    <td><%= service.pay_time %></td>
                    <td>
                      <%= link_to "Edit", edit_admin_service_path(service.id), class: 'btn btn-warning btn-sm' %>
                      <%= link_to "Delete", admin_service_path(service.id), method: :destroy, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>

      
    </div>
  </div>
</div>