config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, skip: [:destroy]
  devise_for :users, skip: [:registrations]

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/send_payroll', to: 'dashboard#send_payroll'
    put '/update_status', to: 'dashboard#update_status' 
    get '/stores/export-weekly', to: 'stores#export_week'
    resources :users do
      member do
        get :toggle_status
      end
    end
    resources :stores
    resources :services
  end
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: [:submitted, :approved, :rejected, :paid]
  belongs_to :user
  belongs_to :store
  has_and_belongs_to_many :services, dependent: :destroy
  validates_presence_of :stk_num, :service_ids, :date

  scope :user_submitted, ->(user, start_date, end_date) { where(:user_id => user.id, :status => "submitted", :date => start_date..end_date)}
  scope :user_rejected, ->(user, start_date, end_date) { where(:user_id => user.id, :status => "rejected", :date => start_date..end_date)}
  scope :user_approved, ->(user, start_date, end_date) { where(:user_id => user.id, :status => "approved", :date => start_date..end_date)}
  scope :user_paid, ->(user, start_date, end_date) { where(:user_id => user.id, :status => "paid", :date => start_date..end_date)}
  scope :store_submitted, ->(store_id, start_date, end_date) { where(:store_id => store_id, :status => "submitted", :date => start_date..end_date)}
  scope :store_rejected, ->(store_id, start_date, end_date) { where(:store_id => store_id, :status => "rejected", :date => start_date..end_date)}
  scope :store_approved, ->(store_id, start_date, end_date) { where(:store_id => store_id, :status => "approved", :date => start_date..end_date)}
  scope :store_paid, ->(store_id, start_date, end_date) { where(:store_id => store_id, :status => "paid", :date => start_date..end_date)}
  scope :current_view, ->(store_id, status, start_date, end_date) { where(:store_id => store_id, :status => status, :date => start_date..end_date)}
  scope :user_posts, ->(user, start_date, end_date) { where(:user_id => user, :date => start_date..end_date) }
  # Ex:- scope :active, -> {where(:active => true)}


  def pay_calc
    time = []
    self.services.each do |s|
      time.push(s.pay_time)
    end
    time.sum
  end

  def self.to_csv
    attributes = %w{dms_id full_name date status stk_num total_pay}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |post|
        csv << [post.user.dms_id, post.user.full_name, post.date, post.status, post.stk_num, post.pay_calc]
      end
    end
  end
  

  def service_list
    hash = {}
    self.services.each do |s|
      hash["#{s.service_name}"] = s.pay_time
    end
    hash
  end
  




  
  
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates_presence_of :first_name, :last_name
  has_many :posts, dependent: :destroy
  has_and_belongs_to_many :stores, dependent: :destroy
  enum status: [:active, :disabled]


  def self.to_csv
    attributes = %w{dms_id full_name store}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << [user.dms_id, user.full_name, user.stores.first.name]
      end
    end
  end
   


  def full_name
    first_name + " " + last_name
  end

  def self.store_member(store_ids)
    includes(:stores).where(stores: { id: store_ids })
  end

  def total_paid(start_date, end_date)
    total = []
    self.posts.where(status: "paid", date: start_date..end_date).each do |t|
      total.push(t.pay_calc)
    end
    total.sum
  end
  

  def totals(start_date, end_date)
    total = []
    self.posts.where(date: start_date..end_date, status: 'paid').each do |t|
      total.push(t.pay_calc)
    end
    total.sum
  end

  def paid_list(start_date, end_date)
    list = []
    self.posts.where(date: start_date..end_date, status: 'paid').each do |item|
      list.push(item.stk_num)
    end
    list
  end
  
  
  
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show]
  before_action :set_form_data, only: [:edit, :new]
  helper_method :store_params, :status_params
  layout :posts_layout

  def index
    if current_user == "ManagerUser" || "AdminUser"
      @submitted = Post.store_submitted(store_params, sort_start, sort_end)
      @rejected = Post.store_rejected(store_params, sort_start, sort_end)
      @approved = Post.store_approved(store_params, sort_start, sort_end)
      @paid = Post.store_paid(store_params, sort_start, sort_end)
      @posts = Post.current_view(store_params, status_params, sort_start, sort_end)
      @store = Store.find(store_params)
    else
      @submitted = Post.user_submitted(current_user, sort_start, sort_end)
      @rejected = Post.user_rejected(current_user, sort_start, sort_end)
      @approved = Post.user_approved(current_user, sort_start, sort_end)
      @paid = Post.user_paid(current_user, sort_start, sort_end)
      @posts = Post.current_view(current_user.stores, status_params, sort_start, sort_end)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(post_params[:user_id])
    @post = Post.new(post_params)
    @post.store_id = @user.stores.first.id
    if @post.save!
      redirect_back fallback_location: posts_path, notice: "#{@post.stk_num} Added Successfully for Date: #{@post.date}!"
    else
      render :new, error: "Error Adding"
    end
  end

  def edit
    @services = Service.where(store_id: current_user.store_ids)
  end
  
  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Vehicle Updated'
    else
      render :edit
    end
  end

  def show
    
  end

  private

  def posts_layout
    if current_user.type == "AdminUser" || current_user.type == "ManagerUser"
      "management"
    else
      "kia"
    end
  end
  

  def set_form_data
    @users = User.store_member(current_user.store_ids)
    @services = Service.where(store_id: current_user.store_ids)
  end

  def store_params
    case current_user.type
    when "AdminUser"
      if params[:store_id].present?
        params[:store_id]
      else
        1
      end
    when "ManagerUser"
      if params[:store_id].present? && current_user.store_ids.include?(params[:store_id].to_i)
        params[:store_id]
      else
        current_user.store_ids.first
      end
    else
      current_user.store_ids.first
    end
  end

  def status_params
    if params[:status].present?
      params[:status]
    else
      "submitted"
    end
  end

  def post_params
    params.require(:post).permit(:stk_num, :comments, :date, :status, :user_id, service_ids:[])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/admin/_paid.html.erb
<div class="modal fade" id="paidModalCenter" tabindex="-1" role="dialog" aria-labelledby="paidModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="paidModalTitle">Update Records</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        How would you like to mark the Following Records?
        <table class="table" id="modal-table" onload="printNames()">
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Submitted", class: "btn btn-primary", name: 'status', value: 'submitted' %>
        <%= f.submit "Approved", class: "btn btn-info", name: 'status', value: 'approved' %>
        <%= f.submit "Paid", class: "btn btn-success", name: 'status', value: 'paid' %>
        <%= f.submit "Rejected", class: "btn btn-danger", name: 'status', value: 'rejected' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/admin/_post_index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <%= previous_week_link(sort_start, sort_end, store_params) %>
    </div>
    <div class="col-md-8">
      <h1><%= @store.name %></h1>
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <%= status_tab("submitted", @submitted.count, "primary") %>
        </li>
        <li class="nav-item">
          <%= status_tab("approved", @approved.count, "info") %>
        </li>
        <li class="nav-item">
          <%= status_tab("rejected", @rejected.count, "danger") %>
        </li>
        <li class="nav-item">
          <%= status_tab("paid", @paid.count, "success") %>
        </li>
      </ul>
      <%= render partial: 'posts/admin/posts', locals: { lists: @posts } %>
    </div>
    <div class="col-md-2">
      <%= next_week_link(sort_start, sort_end, store_params) %>
    </div>
  </div>
</div>

app/views/posts/admin/_posts.html.erb
<%= form_for :post, :url => admin_update_status_path, :html => { :method => :put } do |f| %>
<table class="table table-striped table-sm">
  <tr>
    <th>Detailer</th>
    <th>Date</th>
    <th>Stk Num</th>
    <th>Services</th>
    <th>Update?</th>
    <th>Status</th>
  </tr>
  <tbody>
    <% lists.each do |p| %>
    <tr id="row-<%= p.id %>">
      <td id="name-<%= p.id %>">
        <%= p.user.full_name %>
      </td>
      <td>
        <%= p.date %>
      </td>
      <td id="stk-<%= p.id %>">
        <%= link_to p.stk_num, edit_post_path(p) %>
      </td>
      <td>
        <% p.services.each do |s| %>
        <span class="badge badge-pill badge-secondary">
          <%= s.service_name %></span>
        <% end %>
        <span class="badge badge-pill badge-info" id="total-<%= p.id %>">Total:
          <%= p.pay_calc %></span>
      </td>
      <td>
        <%= check_box_tag "post_ids[]", p.id %>
      </td>
      <td><span class="<%= status_style(p.status) %>">
          <%= p.status.humanize %></span></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= render partial: 'posts/admin/paid', locals: { f: f } %>
<% end %>
<button id="updateRecords" type="button" class="btn btn-info" data-toggle="modal" data-target="#paidModalCenter" onclick="combineInfo()">
  Update Records?
</button>
<script>
  var checked = [];
  var names = [];
  var stkNumbers = [];
  var totals = [];

  var boxes = $('input:checkbox');

  boxes.on('change', function () {
    $('#updateRecords').prop('disabled', !boxes.filter(':checked').length);
  }).trigger('change');

  function getIDs() {
    $("input:checkbox").each(function () {
      var $this = $(this);

      if ($this.is(":checked")) {
        if (checked.includes($this.attr("value")) == false) {
          checked.push($this.attr("value"));
        } else {
          console.log("welp")
        }
      }
    });
  }

  function getNames() {
    for (i = 0; i < checked.length; i++) {
      names.push($('#name-' + checked[i]).text());
      stkNumbers.push($('#stk-' + checked[i]).text());
      totals.push($('#total-' + checked[i]).text());
    }
  }

  function printNames() {
    for (i = 0; i < names.length; i++) {
      $('#modal-table').append("<tr><td>" + names[i] + "</td><td>" + stkNumbers[i] + "</td><td>" + totals[i] + "</tr>");
    }
  }
  function combineInfo() {
    getIDs();
    getNames();
    printNames();
  }


</script>