config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, skip: [:destroy]
  devise_for :users, skip: [:registrations]

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/send_payroll', to: 'dashboard#send_payroll'
    put '/update_status', to: 'dashboard#update_status' 
    get '/stores/export-weekly', to: 'stores#export_week'
    resources :users do
      member do
        get :toggle_status
      end
    end
    resources :stores
    resources :services
  end
end

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Company Wide</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <%= nav_bar_links(current_user) %>
    </ul>
    <span class="navbar-text">
      <%= current_payweek[:days_left] %> Days left to submit payroll.
    </span>
    <%= link_to "Admin Panel", admin_path, class: 'btn btn-primary btn-sm' if current_user.type == "AdminUser" %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm'%>
  </div>
</nav>

app/views/shared/_flash.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

app/views/shared/_user_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= current_user.stores.first.name.humanize %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= active?(root_path) %>">
        <%= link_to "Current Week", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= active?(new_post_path) %>">
        <%= link_to "New Entry", new_post_path, class: 'nav-link' %>
      </li>
    </ul>
    <span class="navbar-text">
      <%= current_payweek[:days_left] %> Days left to submit payroll.
    </span>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm'%>
  </div>
</nav>