config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, skip: [:destroy]
  devise_for :users, skip: [:registrations]

  namespace :admin do
    get '/', to: 'dashboard#index'
    get '/send_payroll', to: 'dashboard#send_payroll'
    put '/update_status', to: 'dashboard#update_status' 
    get '/stores/export-weekly', to: 'stores#export_week'
    resources :users do
      member do
        get :toggle_status
      end
    end
    resources :stores
    resources :services
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates_presence_of :first_name, :last_name
  has_many :posts, dependent: :destroy
  has_and_belongs_to_many :stores, dependent: :destroy
  enum status: [:active, :disabled]


  def self.to_csv
    attributes = %w{dms_id full_name store}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << [user.dms_id, user.full_name, user.stores.first.name]
      end
    end
  end
   


  def full_name
    first_name + " " + last_name
  end

  def self.store_member(store_ids)
    includes(:stores).where(stores: { id: store_ids })
  end

  def total_paid(start_date, end_date)
    total = []
    self.posts.where(status: "paid", date: start_date..end_date).each do |t|
      total.push(t.pay_calc)
    end
    total.sum
  end
  

  def totals(start_date, end_date)
    total = []
    self.posts.where(date: start_date..end_date, status: 'paid').each do |t|
      total.push(t.pay_calc)
    end
    total.sum
  end

  def paid_list(start_date, end_date)
    list = []
    self.posts.where(date: start_date..end_date, status: 'paid').each do |item|
      list.push(item.stk_num)
    end
    list
  end
  
  
  
  
  
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    layout 'admin'
    before_action :authenticate_admin
    before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_status]
    
    def index
      @users = User.all
      @payroll_employees = User.where(type: nil)
      @user = User.new
      @stores = Store.all
      respond_to do |format|
        format.html
        format.csv { send_data @payroll_employees.to_csv, filename: "users-#{Date.today}.csv" }

      end
    end

    def create
      @user = User.new(user_params)
      if @user.save!
        redirect_back fallback_location: admin_users_path, notice: "User Created"
      else
        redirect_back fallback_location: admin_users_path, notice: "Error Creating User"
      end
    end

    def show
      @week_posts = Post.user_posts(@user.id, sort_start, sort_end)
      @week_amts = list_services(@week_posts).to_json
      @month_posts = Post.user_posts(@user.id, Date.today.beginning_of_month, Date.today.end_of_month)
      @month_amts = list_services(@month_posts).to_json
      respond_to do |format|
        format.html
        format.json { render json: @week_amts }
      end
  
    end

    def edit
      @stores = Store.all
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: "#{@user.full_name} has been updated"
      else
        render :edit
      end
    end
    
    def destroy
      @user.delete
      redirect_to admin_users_path, notice: "User Deleted"
    end

    def toggle_status
      if @user.disabled?
        @user.active!
      else
        @user.disabled!
      end
      redirect_back fallback_location: admin_users_path, notice: "#{@user.full_name} has been made #{@user.status.titleize}"
    end
    

    private

    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation, :first_name, :last_name, :type, :dms_id, store_ids:[])
    end

    def set_user
      @user = User.find(params[:id])
    end

    def list_services(posts)
      list = {}
      posts.each do |p|
        list.merge!(p.service_list) { |k, o, n| o + n }
      end
      list
    end
  end
end

app/views/admin/users/_form.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Add User</h5>
      <%= form_for :user, :url => admin_users_path do |f| %>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :username %>
              <%= f.text_field :username, required: true, autofocus: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, required: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, required: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, required: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, required: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, required: true, class: 'form-control form-control-sm' %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <% @stores.each do |store| %>
            <div class="form-check">
              <%= f.check_box :store_ids, { multiple: true }, store.id, false %>
              <%= store.name.titleize %>
            </div>
            <% end %>
          </div>
          <div class="col">
            <div class="form-group">
              <%= f.label :dms_id %>
              <%= f.text_field :dms_id, required: true, class: 'form-control form-control-sm' %>
            </div>
            <div class="form-group">
              <%= f.label :type %>
              <%= f.select(:type, options_for_select([['User', ''], ['Manager', 'ManagerUser'], ['Admin', 'AdminUser']]), class: 'form-control form-control-sm') %>
            </div>
          </div>
        </div>
        <%= f.submit "Add User", class: "btn btn-sm btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add User</h5>
          <%= form_for :user, :url => admin_user_path(@user), :method => :put do |f| %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :username %>
                <%= f.text_field :username, required: true, autofocus: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, required: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, required: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, required: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, required: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, required: true, class: 'form-control form-control-sm' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <% @stores.each do |store| %>
              <div class="form-check">
                <%= f.check_box :store_ids, { multiple: true }, store.id, false %>
                <%= f.label store.name %>
              </div>
              <% end %>
            </div>
            <div class="col">
              <div class="form-group">
                <%= f.label :dms_id %>
                <%= f.text_field :dms_id, required: true, class: 'form-control form-control-sm' %>
              </div>
              <div class="form-group">
                <%= f.label :type %>
                <%= f.select(:type, options_for_select([['User', ''], ['Manager', 'ManagerUser'], ['Admin', 'AdminUser']]), class: 'form-control form-control-sm') %>
              </div>
            </div>
          </div>
          <%= f.submit "Add User", class: "btn btn-sm btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">User Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to "Export Users", admin_users_path(format: "csv"), class: "btn btn-sm btn-outline-secondary" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= render 'form' %>
    <div class="col-md-12">
      <ul class="nav nav-tabs" role="tablist">
        <% @stores.each do |store| %>
          <li class="nav-item">
            <a class="nav-link" href="#store<%= store.id %>" role="tab" data-toggle="tab"><%= store.name %></a>
          </li>
        <% end %>
      </ul>

      <div class="tab-content">
        <% @stores.each do |store| %>
          <div role="tabpanel" class="tab-pane fade" id="store<%= store.id %>">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">User List</h5>
                <table class="table table-striped table-sm">
                  <thead>
                    <tr>
                      <th>Full Name</th>
                      <th>DMS ID</th>
                      <th>Store</th>
                      <th>Type</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% store.users.each do |user| %>
                      <tr>
                        <td><%= link_to user.full_name, admin_user_path(user.id) %></td>
                        <td><%= user.dms_id %></td>
                        <td>
                          <ul>
                            <% user.stores.each do |store| %>
                              <li><span class="badge badge-pill badge-primary"><%= store.name.titleize %></span></li>
                            <% end %>
                          </ul>
                          
                        </td>
                        <td><%= user.type %></td>
                        <td>
                          <% if user.disabled? %>
                            <%= link_to "Activate", toggle_status_admin_user_path(user.id), class: 'btn btn-sm btn-success' %>
                          <% else %>
                            <%= link_to "Disable", toggle_status_admin_user_path(user.id), class: 'btn btn-sm btn-danger' %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">User: <%= @user.full_name %></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= form_tag("/admin/users/#{@user.id}", method: :get) do |s| %>
      Start Date: <%= date_field_tag :start_date, sort_start %>
      End Date: <%= date_field_tag :end_date, sort_end %>
      <%= submit_tag "Update Date", class: 'btn btn-sm btn-info' %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Performance for Week of <%= sort_start %></h6>
          <canvas id="postCount"></canvas>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Performance Current Month</h6>
          <canvas id="currentMonth"></canvas>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h2></h2>
      <table class="table table-striped">
        <thead>
          <th>ID#</th>
          <th>Store</th>
          <th>Services</th>
          <th>Ammount</th>
        </thead>
        <tbody>
          <% @week_posts.each do |post| %>
            <tr>
              <td><%= post.id %></td>
              <td><%= post.store.name %></td>
              <td>
                <ul>
                  <% post.services.each do |service| %>
                    <li><%= service.service_name %> | <%= service.pay_time %></li>
                  <% end %>
                </ul>
              </td>
              <td><%= post.pay_calc %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script ></script>
<script>
 
  var weekServiceName = []
  var weekServiceValue = []
  var monthServName = []
  var monthServValue = []
  var weekAmts = <%= @week_amts.html_safe %>;
  var monthAmts = <%= @month_amts.html_safe %>;

  for(i in weekAmts)
    weekServiceName.push(i);
  
  for(i in weekAmts)
    weekServiceValue.push(weekAmts[i]);

  for(i in monthAmts)
    monthServName.push(i);

  for(i in monthAmts)
    monthServValue.push(monthAmts[i])

  function randomColors(list) {
    var colors = [];
    for(i = 0; i < list.length; i++){
      colors.push('#' + (Math.random().toString(16) + '0000000').slice(2, 8));
    }
    return colors
  }

  var weekCanvas = document.getElementById('postCount').getContext('2d');
  var postCount = new Chart(weekCanvas, {
    type: 'doughnut',
    data: {
      labels: weekServiceName,
      datasets: [{
        data: weekServiceValue,
        backgroundColor: randomColors(weekServiceName),
      }],
    },
  });

  var currentMonth = document.getElementById('currentMonth').getContext('2d');
  var currentMonthPie = new Chart(currentMonth, {
    type: 'doughnut',
    data: {
      labels: monthServName,
      datasets: [{
        data: monthServValue,
        backgroundColor: randomColors(monthServName),
        }],
    }
  });
</script>